name: fund_app
description: "A new Flutter project."
# Prevent publishing this package to pub.dev
publish_to: "none"

# Version and build number for your application
version: 1.0.0+1

environment:
  sdk: ^3.6.0

# Dependencies required for the app to work
dependencies:
  flutter:
    sdk: flutter

  # Cupertino Icons for iOS-style icons
  cupertino_icons: ^1.0.8

  # Your project packages
  awesome_dialog: ^3.3.0
  http: ^1.6.0
  drop_down_list: ^2.1.0
  shared_preferences: ^2.5.3
  geolocator: ^14.0.2

# Dev dependencies for development only (not included in release)
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

# Configuration for flutter_launcher_icons
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "images/Logo.webp"
  min_sdk_android: 21

# Flutter-specific settings
flutter:
  # Include Material Icons font
  uses-material-design: true

  # Assets used in the project
  assets:
    - images/prog.png
    - images/Logo.webp # إذا تريد استخدامه كأيقونة Launcher أيضاً

  # Fonts
  fonts:
    - family: IosevkaCharonMono-Regular
      fonts:
        - asset: fonts/IosevkaCharonMono-Regular.ttf
    # مثال إضافي (يمكنك تفعيله لاحقاً)
    # - family: Schyler
    #   fonts:
    #     - asset: fonts/Schyler-Regular.ttf
    #     - asset: fonts/Schyler-Italic.ttf
    #       style: italic
